### ISSUE TITLE
Adding Sources like KissManga and MangaFox

### ISSUE THREAD

**Issue by Adamlord1** [jparkie/Aizoban#18]
Bro u please try to add these sites they are really fast specially kissmanga

**Comment by jparkie** [comment]
Because of my location, I can't access MangaFox as mostly all the series are licensed such that I can't read them, so I never had the chance to analyze the site directory and its HTML to make a source. The problem with KissManga is that their is no viable option to compile a source into the local database. I would have to load each page of a manga and scrape it into a database. It would take 1 GB of bandwidth and I have no idea how long. Furthermore, CloudFare which hosts KissManga might block my connection when compiling if I did go through every single source. If this is a big source you want, I can retry doing this.

**Comment by Adamlord1** [comment]
I understand that ur location might become trouble but I would like to tell u that mangafox many times suffer from licensed bug even if it is not licenced eg Tokyo ghoul:re and it is not the only one ,there is someway to bypass it the blockade I mean there are some other reader who have been able to bypass it.

For kissmanga actually I am unable to understand what u are saying can u explain in somewhat simpler terms 
Maybe u can use the download manga option app in kissmanga on the title bar to somehow extract mangas I don't exactly know earlier I used to use an app called manga reader which had a panda icon and supported kissmanga however some trouble occurred it got removed like many others . 
Why I really like about kissmanga is that there is rarely any broken pages and download is fast.

Anyway ur app is great it somewhat feels light and fast thanks for making such an amazing application.

**Comment by Adamlord1** [comment]
Another thing I would like to add is even mangahere certain mangas like mushoku tensei are missing.

**Comment by jparkie** [comment]
For the series that are missing in the sources, I just need to update the local database built into the application for a new update. I plan to do it every month.

**Comment by jparkie** [comment]
Regarding sources in general, I try to find websites which are like this: http://www.mangareader.net/popular and http://www.mangareader.net/latest. So two sections, one of which lists series generally with their genres, rank, status, thumbnail, and title, and another which lists latest updates. The problem with KissManga is that its http://kissmanga.com/MangaList only lists series' titles. If I were to include it, there would be no genres nor thumbnails in the catalogue, only when you open up a series would it fetch all its information and thumbnail included. The only solution would be for me to load every single series and build a local database for the catalogue that way. The downside is the overhead in doing so.

**Comment by jparkie** [comment]
For MangaFox, if I can get help bypassing some stuff on my computer, I could implement it. I think MangaFox is owned by the same company as MangaHere and some others, since their site structure and HTML are quite similar. Their search page and manga page are pretty identical. Furthermore, the servers which hosts their images are the same format.

**Comment by Adamlord1** [comment]
I dont know check this out if u hold ur touch on any item of manga list in kissmanga will bring up its details
