### ISSUE TITLE
View pages from top

### ISSUE THREAD

**Issue by Tabaluga** [jparkie/Aizoban#42]
Plesse add an Option which views every page from top. It's very Bad to scroll every page up to read them from the beginning. Best example "Girls the Wild". Best regards

**Comment by jparkie** [comment]
Okay. For Version 2.0.+ which I am working on, I'll try to accomplish this. I don't know how well it will be implemented as I am abandoning my custom image viewer for someone else's. The other person's image viewing library uses tiled pyramid image segregation such that images from Girls the Wild can be displayed at their full resolution (even 20,000 by 20,000 pixels) without lowering the resolution and, thus, the quality.I am going to study how his library works and see if I can reasonably implement this.

**Comment by Tabaluga** [comment]
Thanks. I hope I explained the issue very well, cause on every page I need to scroll up to read from top to bottom. This behaviour is currently very awkward and not user friendly in my opinion so I hope you can fix this issue very soon. Perhaps you can inspect the code of other open source manga readers to archieve this. Besteht regards

**Comment by jparkie** [comment]
I understood what you meant. In the current code, if the page is zoomed, it centers the page horizontally and vertically, so that it is not out of bounds. 

However, I am going to abandon my current image viewer for a different one. There are barely any open sourced comic readers applicable to study for this application. The ones which are written in Java and are for Android are either outdated or poorly implemented. 

Barely any application except for Google's native Gallery application uses tiled pyramid image segregation algorithms, but their implementation is very impractical to adapt. Thus, I am going to use someone else's library which implements the algorithm in more modern methods. As the 3.0.0 version was released for the library yesterday, I have to read the code to see how I can set the location of the zooming logic. Overall, this issue might be fixed in Version 2.0.+ and not in any of the Version 1.2.+ releases.
