### ISSUE TITLE
'Current Download Directory' not saving to SD...

### ISSUE THREAD

**Issue by gr01d** [jparkie/Aizoban#45]
Current Download Directory not saving to SD card (/sdcard0/com.jparkie/aizoban) but to System Data only (data/data/com.jparkie.aizoban = no system storage space..

**Comment by jparkie** [comment]
In the settings, you choose the microSD card directory? If you did, and it is failing, I need more information about the device, the manufacturer, the Android version (and whether it is stock or manufactured alternative), and if you are on the latest version of the application.

**Comment by frostnium** [comment]
Hi, I'm also having the same issue since having a phone with small internal memory is really troublesome. I can't save downloaded mangas to SD card and the "move to SD Card" option is also unavailable. I'm on a Lenovo a369i, android version 4.2.2(stock), and is on Aizoban version 1.2.5 (which I assume is the latest one).

**Comment by butterfist** [comment]
Frostnium unfortunately the support has been stopped from jacob

**Comment by frostnium** [comment]
Aww, shame. Thanks for the heads up anyways!
